site:  https://numpy.org/devdocs/reference/generated/numpy.concatenate.html#numpy.concatenate
# STUDENT'S GRATES
Let's take a simple example and increment it gradually


In [1]:
import numpy as np



From one value to 3 dimensions

In [2]:
# The student got a mark for a single leason

# Array with shape
grades_array = np.array([1])
print("1. use array:",grades_array, grades_array.shape, ".           type:",type(grades_array),".  type value on this array:",grades_array.dtype)

# Number 
grades_number = np.array(1)
print("2. use Nr:",grades_number, "shape:",grades_number.shape, ".   type:",type(grades_number),".  type value on this array:",grades_number.dtype)

#  -> set the type value in this array --v
grades_number = np.array([10,1], dtype =  np.int8)
print("3. use Nr:",grades_number,".   shape:" , grades_number.shape, ".   type:",type(grades_number),".  type value on this array:",grades_number.dtype)

# What hapen if the value is pas type value
grades_number = np.array(1000, dtype =  np.int8)
print("4. Nr:",grades_number, ".  type value on this array:",grades_number.dtype,"transforn the number in bit and retransform the last 8th didit in decimal result is -24")


1. use array: [1] (1,) .           type: <class 'numpy.ndarray'> .  type value on this array: int64
2. use Nr: 1 shape: () .   type: <class 'numpy.ndarray'> .  type value on this array: int64
3. use Nr: [10  1] .   shape: (2,) .   type: <class 'numpy.ndarray'> .  type value on this array: int8
4. Nr: -24 .  type value on this array: int8 transforn the number in bit and retransform the last 8th didit in decimal result is -24


In [3]:
# The student got a mark for each (7) lessons
grades_7_lesons = np.array([10,9,9,8,8,10,10],  dtype = np.int8)
print("use array:",grades_7_lesons, grades_7_lesons.shape, ".        type:",type(grades_7_lesons),".  type value on this array:",grades_7_lesons.dtype)


use array: [10  9  9  8  8 10 10] (7,) .        type: <class 'numpy.ndarray'> .  type value on this array: int8


Use append for add next grades

In [4]:
grades_7_lesons = np.array(10,  dtype = np.int8)
grades_7_lesons = np.append(grades_7_lesons,[9,9,8,8,10,10])
print("use array:",grades_7_lesons,"shape:", grades_7_lesons.shape, ".        type:",type(grades_7_lesons),".  type value on this array:",grades_7_lesons.dtype)
# in numpy the array is making a clone an this set new default type. 


use array: [10  9  9  8  8 10 10] shape: (7,) .        type: <class 'numpy.ndarray'> .  type value on this array: int64


In [5]:
# HW1: fiind a nother solution to add the marks to an existing array
grades = np.array([10],dtype=np.int8)

#  for insert:    index---v       v--- value 
#                         v       v
grades =np.insert( grades,1,[9,9,8,8,10,10])

print(grades,grades.dtype)

[10  9  9  8  8 10 10] int8


In [6]:
# agroup of 3 students marks
#                arguments------v | Students ------v
#                               v | Lesonss----- v v
grades = np.random.randint(low=0,high=10,  size=(7,5), dtype= np.int8)
print("   Grades",)
print(grades,"Grades shape:",grades.shape,grades.dtype)

   Grades
[[6 6 0 8 1]
 [2 1 3 7 4]
 [8 6 5 6 6]
 [2 5 5 4 0]
 [5 9 3 4 4]
 [5 2 7 7 0]
 [5 7 5 4 1]] Grades shape: (7, 5) int8


In [7]:
#                                   reshape argument
# agroup of 3 students marks
#     arguments------v | Students ------v
#                    v | Lesonss----- v v
grades = np.reshape(         grades, (5,7))
print("  reshape Grades ",)
print(grades,"Grades reshapes:",grades.shape,grades.dtype)


  reshape Grades 
[[6 6 0 8 1 2 1]
 [3 7 4 8 6 5 6]
 [6 2 5 5 4 0 5]
 [9 3 4 4 5 2 7]
 [7 0 5 7 5 4 1]] Grades reshapes: (5, 7) int8


In [8]:
#                           Grades:regular shape
print("Grades:regular shape")
grades = np.random.randint(low=0,high=11,  size=(7,5), dtype= np.int8)
print(grades)
print()

#                      Transpose argument(  rotation to 90 degrees)
# agroup of 3 students marks | AXES----v
#     arguments------v | Students ------v
#                    v | Lesonss----- v v
grades = np.transpose(grades,        (1,0))
print("  transpose degrees ",)
print(grades,"Grades (transpose) rotation to 90 degrees:",grades.shape,grades.dtype)


Grades:regular shape
[[ 6  4  8  0  7]
 [ 1 10  7  0  5]
 [ 6  1 10  4  8]
 [ 6 10  3  6  7]
 [ 0  0  4  9  5]
 [ 7  0  2  8  9]
 [ 7 10  7  0  2]]

  transpose degrees 
[[ 6  1  6  6  0  7  7]
 [ 4 10  1 10  0  0 10]
 [ 8  7 10  3  4  2  7]
 [ 0  0  4  6  9  8  0]
 [ 7  5  8  7  5  9  2]] Grades (transpose) rotation to 90 degrees: (5, 7) int8


In [9]:
# print the second student last grades

# [[10  9 10  3  5  9  2]
#  [ 6  6  3  2  6  0 (5)]
#  [ 1  2  8  4  5  2  4]
#  [ 4  2  0 10  7  6  0]
#  [ 5  8  6  3  4 10  1]] 

# for regular py
print(grades[1][6])
# for shortcut np
print(grades[1,6])

10
10


In [10]:
# optain marks for 3 groups of students each for 7 lessons

# agroup of 3 students marks 
#            arguments------v |       Students ------v
#                           v |       Lesonss----- v v
#                           v |       Groups-----v v v 
print("          Grades:")# v |                  v v v
grades = np.random.randint(low=0,high=11,  size=(3,5,7), dtype= np.int8)
print(grades,"Grades shape:",grades.shape,grades.dtype)


          Grades:
[[[ 9  5  3  2  3  6  5]
  [ 9  4  1 10  4  2  4]
  [ 5  3  5  9  0  9 10]
  [ 2  8  1  6  4 10  7]
  [ 7  2  6  7  3  0  8]]

 [[10  8  6  8  7  0  2]
  [ 0  0  1  4  7  5  9]
  [ 9  5  9  0  0  2  7]
  [ 5  7  7  2 10 10  0]
  [ 0  8  0  2  8  7  6]]

 [[ 4  6  6  8  4  5  7]
  [ 8 10  6  1  3  6  5]
  [ 3  7  1  7  9  9  8]
  [ 6  2  7  4  9  7 10]
  [ 6  9  8  4  1  2  5]]] Grades shape: (3, 5, 7) int8


In [11]:
# HW2: while have data for first group (5,7) add the next two
#                    CONCATENATE
grades_g1 = np.random.randint(low=0,high=11,  size=(1,5,7), dtype= np.int8)
print(grades_g1)
grades_g2_g3 = np.random.randint(low=0,high=11,  size=(2,5,7), dtype= np.int8)
grades = np.concatenate((grades_g1, grades_g2_g3), axis=0)
print("          Grades:")
print(grades,"Grades shape:",grades.shape,grades.dtype)


[[[ 8  4  2  8  3  1  0]
  [ 3  1  0 10  2  8  7]
  [ 9  0  4  2  4  8  6]
  [ 9  8  5  7  6  0  7]
  [ 2  7 10  8 10  3  4]]]
          Grades:
[[[ 8  4  2  8  3  1  0]
  [ 3  1  0 10  2  8  7]
  [ 9  0  4  2  4  8  6]
  [ 9  8  5  7  6  0  7]
  [ 2  7 10  8 10  3  4]]

 [[10  2  4  3  9  1  8]
  [ 1  9  6 10  9  6  7]
  [ 5  2  4  3 10  5  9]
  [ 1  9  4  1  9  3  7]
  [ 0  7  3  8  5  7  0]]

 [[ 6 10  4  2  7  2  5]
  [ 1  5  0  2 10  9  7]
  [ 0  8  1  5 10  8  0]
  [10  5  2  0  5  3  7]
  [ 0  0 10  2  2  4  7]]] Grades shape: (3, 5, 7) int8


In [12]:
grades = np.array([[[ 6,  8,  6,  4,  4,  7,  9,],
                    [ 2,  4,  3,  2,  3,  0,  1,],
                    [ 3,  8,  7,  9,  4, 10,  5,],
                    [ 2,  1,  2,  7,  9, 10,  7,],
                    [10,  9, 10, 10,  9,  6,  8,],],

                   [[ 3,  9,  6,  5,  0,  2, 10,],
                    [ 2,  5,  5,  9, 10,  6,  4,],
                    [ 9,  6,  9,  3,  3,  8,  1,],
                    [ 9,  9,  1,  6,  9,  8,  8,],
                    [ 1,  0,  7,  0,  7,  3,  8,],],
 
                   [[ 6,  4,  4,  9, 10,  3,  8,],
                    [ 0,  1,  8,  8,  0,  7,  5,],
                    [ 5,  6,  5,  4,  6,  3,  4,],
                    [ 8,  2,  5,  2,  7,  0,  4,],
                    [ 6,  0,  1,  4,  7,  5,  6,],]], dtype=np.int8)


###   AXES
<img src="axis_vizualization _numpy.png" style="width:700px;height 700px"/>

In [13]:
#                 sum  AXES=
print(" sum axe->[0]:","\n",np.sum(grades, axis=0))
print(" sum axe->[1]:","\n",np.sum(grades, axis=1))
print(" sum axe->[2]:","\n",np.sum(grades, axis=2,keepdims=True))


 sum axe->[0]: 
 [[15 21 16 18 14 12 27]
 [ 4 10 16 19 13 13 10]
 [17 20 21 16 13 21 10]
 [19 12  8 15 25 18 19]
 [17  9 18 14 23 14 22]]
 sum axe->[1]: 
 [[23 30 28 32 29 33 30]
 [24 29 28 23 29 27 31]
 [25 13 23 27 30 18 27]]
 sum axe->[2]: 
 [[[44]
  [15]
  [46]
  [38]
  [62]]

 [[35]
  [41]
  [39]
  [50]
  [26]]

 [[44]
  [29]
  [33]
  [28]
  [29]]]


solve: mean(avg),max,min

In [14]:

print("          Grades:")
print(grades, "   Grades shape:",grades.shape,grades.dtype)


print("\n"," Average per University:",np.mean(grades))
print("\n"," Average per Group :",np.mean(grades, axis = (1,2)))
print("\n"," Average per Group[0] :",np.mean(grades[0]))

          Grades:
[[[ 6  8  6  4  4  7  9]
  [ 2  4  3  2  3  0  1]
  [ 3  8  7  9  4 10  5]
  [ 2  1  2  7  9 10  7]
  [10  9 10 10  9  6  8]]

 [[ 3  9  6  5  0  2 10]
  [ 2  5  5  9 10  6  4]
  [ 9  6  9  3  3  8  1]
  [ 9  9  1  6  9  8  8]
  [ 1  0  7  0  7  3  8]]

 [[ 6  4  4  9 10  3  8]
  [ 0  1  8  8  0  7  5]
  [ 5  6  5  4  6  3  4]
  [ 8  2  5  2  7  0  4]
  [ 6  0  1  4  7  5  6]]]    Grades shape: (3, 5, 7) int8

  Average per University: 5.3238095238095235

  Average per Group : [5.85714286 5.45714286 4.65714286]

  Average per Group[0] : 5.857142857142857


In [15]:
# HW3: calculate the mean grades for each lessons ->(7,)
print("\n"," Average per lessons :",np.mean(grades, axis = (0,1)))




  Average per lessons : [4.8        4.8        5.26666667 5.46666667 5.86666667 5.2
 5.86666667]


In [16]:
#      Max per group
print("Max per group", np.max(grades,axis =(1,2)))

# keep same dimension for output
print("Max per group", np.max(grades,axis =(1,2),keepdims=True))


Max per group [10 10 10]
Max per group [[[10]]

 [[10]]

 [[10]]]


In [17]:
# HW4: Find the max grades for each students
print("Max grades for each students ", np.max(grades,axis =(2),keepdims=True))


Max grades for each students  [[[ 9]
  [ 4]
  [10]
  [10]
  [10]]

 [[10]
  [10]
  [ 9]
  [ 9]
  [ 8]]

 [[10]
  [ 8]
  [ 6]
  [ 8]
  [ 7]]]


In [18]:
# HW5: find the min grade for each group
print("Min per group", np.min(grades,axis =(1,2),keepdims=True))


Min per group [[[0]]

 [[0]]

 [[0]]]
