In [14]:
import numpy as np

In [15]:
#        INSERT
grades = np.array([10],dtype=np.int8)
grades =np.insert( grades,1,[9,9,8,8,10,10])

print(grades,grades.dtype)

[10  9  9  8  8 10 10] int8


In [16]:
#                    CONCATENATE
grades_g1 = np.random.randint(low=0,high=11,  size=(1,5,7), dtype= np.int8)
print(grades_g1)
grades_g2_g3 = np.random.randint(low=0,high=11,  size=(2,5,7), dtype= np.int8)
grades = np.concatenate((grades_g1, grades_g2_g3), axis=0)
print("          Grades:")
print(grades,"Grades shape:",grades.shape,grades.dtype)

[[[10  0  1  9  3  9  8]
  [ 9  7  9  2  9  5  4]
  [ 1  8  0  4  0  8  5]
  [ 1  8  1 10 10  8  7]
  [ 6  2  4 10  1  8  2]]]
          Grades:
[[[10  0  1  9  3  9  8]
  [ 9  7  9  2  9  5  4]
  [ 1  8  0  4  0  8  5]
  [ 1  8  1 10 10  8  7]
  [ 6  2  4 10  1  8  2]]

 [[ 5 10  9  4 10 10  4]
  [ 7  0  2  3  6  9  2]
  [ 5  2 10  6  4  8  2]
  [ 5 10  9 10  8  6  9]
  [ 7  0  3  9  3  1  1]]

 [[ 8  8  8 10 10  7  8]
  [ 7  2  3  9  6  2  7]
  [ 4 10 10 10  0  9  5]
  [ 6  6  5  0  2  5 10]
  [ 6  1  7  3  2  4  6]]] Grades shape: (3, 5, 7) int8


In [17]:
grades = np.array([[[ 6,  8,  6,  4,  4,  7,  9,],
                    [ 2,  4,  3,  2,  3,  0,  1,],
                    [ 3,  8,  7,  9,  4, 10,  5,],
                    [ 2,  1,  2,  7,  9, 10,  7,],
                    [10,  9, 10, 10,  9,  6,  8,],],

                   [[ 3,  9,  6,  5,  0,  2, 10,],
                    [ 2,  5,  5,  9, 10,  6,  4,],
                    [ 9,  6,  9,  3,  3,  8,  1,],
                    [ 9,  9,  1,  6,  9,  8,  8,],
                    [ 1,  0,  7,  0,  7,  3,  8,],],
 
                   [[ 6,  4,  4,  9, 10,  3,  8,],
                    [ 0,  1,  8,  8,  0,  7,  5,],
                    [ 5,  6,  5,  4,  6,  3,  4,],
                    [ 8,  2,  5,  2,  7,  0,  4,],
                    [ 6,  0,  1,  4,  7,  5,  6,],]], dtype=np.int8)


In [18]:
#     men(AVG) per lessons 
print("\n"," Average per lessons :",np.mean(grades, axis = (0,1)))


  Average per lessons : [4.8        4.8        5.26666667 5.46666667 5.86666667 5.2
 5.86666667]


In [19]:
#  max grades for each students
print("Max grades for each students ", np.max(grades,axis =(2),keepdims=True))


Max grades for each students  [[[ 9]
  [ 4]
  [10]
  [10]
  [10]]

 [[10]
  [10]
  [ 9]
  [ 9]
  [ 8]]

 [[10]
  [ 8]
  [ 6]
  [ 8]
  [ 7]]]


In [20]:
#        min grade for each group
print("Min per group", np.min(grades,axis =(1,2),keepdims=True))


Min per group [[[0]]

 [[0]]

 [[0]]]
